const express=require('express')
const app=express()
const dotenv=require('dotenv')
const path=require('path')
const connectDatabase=require('../backend/config/connectDatabase')
dotenv.config({path:path.join(__dirname,'config','config.env')})
const products=require('../backend/routes/product')
const orders=require('../backend/routes/order')
const cors=require('cors')
app.use(cors())
app.use(express.json())
app.use('/api/v1/',products)
app.use('/api/v1',orders)
app.listen(process.env.PORT,()=>{
    console.log(`Listening at http://localhost:${process.env.PORT}`)
})
connectDatabase();